# Generated by Django 3.2.12 on 2024-01-17 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('population', models.IntegerField()),
                ('habitat', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=250)),
            ],
        ),
    ]
