# Generated by Django 3.2.12 on 2024-01-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finch',
            name='population',
            field=models.CharField(max_length=50),
        ),
    ]
